HTTPS Work - Removed unneeded server config from AddressBook -  Changed default authority address from http to ocp - Generated SSL certs on startup, if missing - Started SSL connector on startup - Made tests override default authority to http (shouldn't hit relay server during tests) - Add SSL config - Updated docker-compose.yml files in windows and unix to expose 5796 for https

diff --git a/install/unix/start b/install/unix/start
--- a/install/unix/start
+++ b/install/unix/start
@@ -1,31 +1,58 @@
 #!/bin/bash
 export OPENCOLA_HOME=~/.opencola
 
+if [[ ! -d $OPENCOLA_HOME/storage ]]; then
+  echo "Creating storage"
+  mkdir -p $OPENCOLA_HOME/storage
+  cp -r ../opencola/storage/* $OPENCOLA_HOME/storage 
+fi
 
-if [[ -d $OPENCOLA_HOME/storage ]]
+CERT_DIR="$OPENCOLA_HOME/storage/cert"
+if [ ! -d "$CERT_DIR" ] || [ ! -f "$CERT_DIR/gen-ssl-cert" ]; then
+  echo "Creating cert directory"
+  cp -r ../opencola/storage/cert "$OPENCOLA_HOME/storage/"
+fi
+
+if [ -e "$OPENCOLA_HOME/storage/cert/opencola-ssl.der" ]
 then
-echo "Storage already exists"
+  echo "SSL certificate found"
+  CERT_EXISTED=true
 else
-echo "Creating storage"
-mkdir -p $OPENCOLA_HOME/storage
-cp -r ../opencola/storage/* $OPENCOLA_HOME/storage 
+  echo "No SSL certificate found"
+  CERT_EXISTED=false
 fi
 
 docker-compose --version 1>/dev/null
 if [ $? -ne 0 ] 
 then
-echo $'\e[31mUnable to execute docker-compose.\e[0m Is Docker [https://docs.docker.com/get-docker/] installed?'
-exit 1
+  echo $'\e[31mUnable to execute docker-compose.\e[0m Is Docker [https://docs.docker.com/get-docker/] installed?'
+  exit 1
 fi
 
 docker-compose -p opencola up --build -d 1>/dev/null
 if [ $? -eq 0 ] 
 then
-echo  $'\e[0;32mOpenCola has started:\e[0m configure docker to run at startup so you do not have to manually start OpenCola again'
+  echo  $'\e[0;32mOpenCola has started:\e[0m configure docker to run at startup so you do not have to manually start OpenCola again'
 else
-echo $'\e[31mUnable to start OpenCola.\e[0m Is docker running [try "open /Applications/Docker.app/"]? Is the port already in use?'
+  echo $'\e[31mUnable to start OpenCola.\e[0m Is docker running [try "open /Applications/Docker.app/"]? Is the port already in use?'
 exit 2
 fi
 
-echo "Visit http://localhost:5795 to get started"
+if ! $CERT_EXISTED
+then
+  echo "Waiting for certificate creation"
+  sleep 10 # Give the server some time to start and gen certs, if needed
+  if [ -e "$OPENCOLA_HOME/storage/cert/opencola-ssl.der" ]
+  then
+    echo "New certs have been created. Install (y/n)?"
+    read -r
+    if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]
+    then
+      pushd $OPENCOLA_HOME/storage/cert/
+      sh install-cert
+      popd
+    fi
+  fi
+fi
 
+echo "Server started - default addresses http://localhost:5795, https://localhost:5796"
